# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('IdAppel', models.AutoField(primary_key=True, serialize=False)),
                ('DateAppel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appelant',
            fields=[
                ('IdAppelant', models.AutoField(primary_key=True, serialize=False)),
                ('PrenomAppelant', models.CharField(max_length=50)),
                ('NomAppelant', models.CharField(max_length=50)),
                ('TelephoneAppelant', models.CharField(max_length=9)),
                ('VilleAppelant', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateService', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('IdCentre', models.AutoField(primary_key=True, serialize=False)),
                ('NomCentre', models.CharField(max_length=50)),
                ('AdresseCentre', models.CharField(max_length=50)),
                ('Capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='etre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateEntree', models.DateTimeField()),
                ('DateSortie', models.DateTimeField()),
                ('TypeHebergement', models.CharField(max_length=20)),
                ('OrientationSortie', models.CharField(max_length=30)),
                ('IdCentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Centre')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('NumeroPersonne', models.AutoField(primary_key=True, serialize=False)),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Nationalite', models.CharField(max_length=30)),
                ('SuiviInfo', models.CharField(max_length=100)),
                ('DateSignalement', models.DateTimeField()),
                ('IdAppelant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Appelant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('IdService', models.AutoField(primary_key=True, serialize=False)),
                ('NatureService', models.CharField(max_length=50)),
                ('LibelleService', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('IdSituation', models.AutoField(primary_key=True, serialize=False)),
                ('LibelleSituation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSituation',
            fields=[
                ('IdTypeSituation', models.AutoField(primary_key=True, serialize=False)),
                ('LibelleTypeSituation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='situation',
            name='IdTypeSituation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.TypeSituation'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='NumeroPersonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Personne'),
        ),
        migrations.AddField(
            model_name='etre',
            name='IdSituation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Situation'),
        ),
        migrations.AddField(
            model_name='etre',
            name='NumeroPersonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Personne'),
        ),
        migrations.AddField(
            model_name='beneficier',
            name='IdService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Service'),
        ),
        migrations.AddField(
            model_name='beneficier',
            name='NumeroPersonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Personne'),
        ),
        migrations.AddField(
            model_name='appel',
            name='IdAppelant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Appelant'),
        ),
    ]
