# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='Sexe',
            field=models.CharField(choices=[('Garçon', 'Garçon'), ('Fille', 'Fille')], default='Garçon', max_length=10),
        ),
    ]
