# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0002_personne_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='Ethnie',
            field=models.CharField(choices=[('wolof', 'wolof'), ('sérére', 'sérére'), ('diola', 'diola'), ('lébou', 'lébou'), ('toucouleur', 'toucouleur'), ('peul', 'peul'), ('bambara/manding', 'bambara/manding'), ('manjack', 'manjack'), ('soninké', 'soninké'), ('autres', 'autres'), ('NSP', 'NSP'), ('sous-régions', 'sous-régions'), ('afrique', 'afrique')], default='wolof', max_length=50),
        ),
        migrations.AddField(
            model_name='personne',
            name='StructureAcceuil',
            field=models.CharField(choices=[('venu avec sa mère', 'venu avec sa mère'), ('SAO', 'SAO'), ('AEMO', 'AEMO'), ('Famille', 'Famille'), ('communauté', 'communauté'), ('né à la Maison rose', 'né à la Maison rose'), ("forces de l' ordre", "forces de l'ordre"), ('structures sanitaires', 'structures sanitaires'), ('partenaires sociaux', 'partenaires sociaux'), ('pouponnière', 'pouponnière'), ('médias', 'médias'), ("venu d'elle/de lui-même", "venu d'elle/de lui-même"), ('autres', 'autres')], default='SAO', max_length=50),
        ),
        migrations.AddField(
            model_name='personne',
            name='TypeSignalement',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Téléphone', 'Téléphone'), ('déclaration de recherche', 'déclaration de recherche')], default='Direct', max_length=50),
        ),
    ]
