# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0003_auto_20161228_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='Prenom',
            field=models.CharField(max_length=50, verbose_name='Prénom de la personne'),
        ),
    ]
