# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0005_auto_20170109_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='DateAppel',
            field=models.DateTimeField(verbose_name="Date et heure de l'appel"),
        ),
        migrations.AlterField(
            model_name='appelant',
            name='NomAppelant',
            field=models.CharField(max_length=50, verbose_name='Nom de la personne appelant'),
        ),
        migrations.AlterField(
            model_name='appelant',
            name='PrenomAppelant',
            field=models.CharField(max_length=50, verbose_name='Prénom de la personne appelant'),
        ),
        migrations.AlterField(
            model_name='appelant',
            name='TelephoneAppelant',
            field=models.CharField(max_length=9, verbose_name='Téléphone de la personne appelant'),
        ),
        migrations.AlterField(
            model_name='appelant',
            name='VilleAppelant',
            field=models.CharField(max_length=30, verbose_name='Ville de la personne appelant'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='DateEntree',
            field=models.DateTimeField(verbose_name="Date et heure du début de l'hebergement"),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='DateSortie',
            field=models.DateTimeField(verbose_name="Date et heure de la fin de l'hebergement"),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='OrientationSortie',
            field=models.CharField(max_length=30, verbose_name='Orientation à la sortie'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='TypeHebergement',
            field=models.CharField(max_length=20, verbose_name="Nature de l'hebergement"),
        ),
        migrations.AlterField(
            model_name='service',
            name='LibelleService',
            field=models.CharField(max_length=50, verbose_name='Libellé du service reçu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='NatureService',
            field=models.CharField(max_length=50, verbose_name='Nature du service'),
        ),
        migrations.AlterField(
            model_name='typesituation',
            name='LibelleTypeSituation',
            field=models.CharField(max_length=50, verbose_name='Type de situation'),
        ),
    ]
